=== BrechtDeMan/WebAudioEvaluationTool/test-schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- define simple elements-->
  <xs:element name="statement" type="xs:string"/>
  <xs:element name="metricenable" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  
  <!-- define simple attributes-->
  <xs:attribute name="id" type="xs:ID"/>
  <xs:attribute name="mandatory" type="xs:boolean"/>
  <xs:attribute name="name" type="xs:string"/>
  
  <!-- define complex elements-->
  <xs:element name="waet">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="setup" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="page" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="setup">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="survey" minOccurs="0" maxOccurs="2"/>
        <xs:element ref="metric" maxOccurs="1"/>
        <xs:element ref="interface" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="interface" type="xs:string" use="required"/>
      <xs:attribute name="projectReturn" type="xs:string" use="required"/>
      <xs:attribute name="randomiseOrder" type="xs:boolean" default="false"/>
      <xs:attribute name="testPages" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
      <xs:attribute name="sampleRate" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="page">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
        <xs:element name="commentboxprefix" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="interface" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="audioelement" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="commentquestion" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="survey" minOccurs="0" maxOccurs="2"/>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="hostURL" type="xs:anyURI" default=""/>
      <xs:attribute name="randomiseOrder" type="xs:boolean" default="false"/>
      <xs:attribute name="repeatCount" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="loop" type="xs:boolean" default="false"/>
      <xs:attribute name="showElementComments" type="xs:boolean" default="false"/>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="metric">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="metricenable" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="interface">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
        <xs:element name="interfaceoption" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="check"/>
                  <xs:enumeration value="show"/>
                  <xs:enumeration value="option"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute name="min" type="xs:decimal" use="optional"/>
            <xs:attribute name="max" type="xs:decimal" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="scales" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="scalelabel" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="position" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:nonNegativeInteger">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="100"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute ref="name" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="audioelement">
    <xs:complexType>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="url" type="xs:anyURI" use="required"/>
      <xs:attribute name="gain" type="xs:decimal" default="0"/>
      <xs:attribute name="type" default="normal">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="normal"/>
            <xs:enumeration value="anchor"/>
            <xs:enumeration value="reference"/>
            <xs:enumeration value="outside-reference"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="marker" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="commentquestion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="statement" minOccurs="0" maxOccurs="1"/>
        <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute ref="name"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="type" default="question">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="question"/>
            <xs:enumeration value="radio"/>
            <xs:enumeration value="checkbox"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="survey">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="surveyentry" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="statement" minOccurs="1" maxOccurs="1"/>
              <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="name"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute ref="id"/>
            <xs:attribute ref="mandatory"/>
            <xs:attribute name="min" type="xs:decimal"/>
            <xs:attribute name="max" type="xs:decimal"/>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="statement"/>
                  <xs:enumeration value="question"/>
                  <xs:enumeration value="number"/>
                  <xs:enumeration value="radio"/>
                  <xs:enumeration value="checkbox"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="boxsize" default="normal">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="normal"/>
                  <xs:enumeration value="large"/>
                  <xs:enumeration value="small"/>
                  <xs:enumeration value="huge"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="location">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="before"/>
            <xs:enumeration value="pre"/>
            <xs:enumeration value="after"/>
            <xs:enumeration value="post"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== BrechtDeMan/WebAudioEvaluationTool/html/tests/examples/APE_example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
    <waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
        <setup interface="APE" projectReturn="save.php" randomiseOrder='true' poolSize="2" loudness="-23">
            <calibration checkFrequencies="true" checkLevels="true" checkChannels="true" />
            <survey location="before">
                <surveyquestion id="sessionId" mandatory="true">
                    <statement>Please enter your name.</statement>
                    <conditional check="equals" value="John" jumpToOnPass="test-intro" jumpToOnFail="checkboxtest" />
                </surveyquestion>
                <surveycheckbox id="checkboxtest" mandatory="true" min="2" max="4" randomise="true">
                    <statement>Please select with which activities you have any experience (example checkbox question)</statement>
                    <option name="musician">Playing a musical instrument</option>
                    <option name="soundengineer">Recording or mixing audio</option>
                    <option name="developer">Developing audio software</option>
                    <option name="hwdesigner">Designing or building audio hardware</option>
                    <option name="researcher">Research in the field of audio</option>
                </surveycheckbox>
                <surveyquestion id="instrument" mandatory="false">
                    <statement>What instrument did you play?</statement>
                </surveyquestion>
                <surveystatement id="test-intro">
                    <statement>This is an example of an 'APE'-style test, with two pages, using the test stimuli in 'example_eval/'.</statement>
                </surveystatement>
            </survey>
            <survey location="after">
                <surveyquestion id="location" mandatory="true" boxsize="large">
                    <statement>Please enter your location. (example mandatory text question)</statement>
                </surveyquestion>
                <surveynumber id="age" min="0">
                    <statement>Please enter your age (example non-mandatory number question)</statement>
                </surveynumber>
                <surveyradio id="rating">
                    <statement>Please rate this interface (example radio button question)</statement>
                    <option name="bad">Bad</option>
                    <option name="poor">Poor</option>
                    <option name="good">Good</option>
                    <option name="great">Great</option>
                </surveyradio>
                <surveystatement id="thankyou">
                    <statement>Thank you for taking this listening test. Please click 'submit' and your results will appear in the 'saves/' folder.</statement>
                </surveystatement>
            </survey>
            <metric>
                <metricenable>testTimer</metricenable>
                <metricenable>elementTimer</metricenable>
                <metricenable>elementInitialPosition</metricenable>
                <metricenable>elementTracker</metricenable>
                <metricenable>elementFlagListenedTo</metricenable>
                <metricenable>elementFlagMoved</metricenable>
                <metricenable>elementListenTracker</metricenable>
            </metric>
            <interface>
                <interfaceoption type="check" name="fragmentMoved" />
                <interfaceoption type="check" name="fragmentPlayed" />
                <interfaceoption type="check" name="scalerange" min="25" max="75" />
                <interfaceoption type="show" name='playhead' />
                <interfaceoption type="show" name="page-count" />
                <interfaceoption type="show" name="comments" />
            </interface>
        </setup>
        <page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='true' synchronous="true" loudness="-12">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface name="preference">
                <title>Preference</title>
                <scales>
                    <scalelabel position="0">Min</scalelabel>
                    <scalelabel position="100">Max</scalelabel>
                    <scalelabel position="50">Middle</scalelabel>
                    <scalelabel position="20">20</scalelabel>
                </scales>
            </interface>
            <interface name="depth">
                <title>Depth</title>
                <scales>
                    <scalelabel position="0">Low</scalelabel>
                    <scalelabel position="100">High</scalelabel>
                    <scalelabel position="50">Middle</scalelabel>
                    <scalelabel position="50">Middle</scalelabel>
                </scales>
            </interface>
            <audioelement url="0.wav" id="track-0" type="anchor" />
            <audioelement url="1.wav" id="track-1" />
            <audioelement url="2.wav" id="track-2" />
            <audioelement url="3.wav" id="track-3" />
            <audioelement url="4.wav" id="track-4" />
            <survey location="before">
                <surveyentry type="statement" id="test-0-intro">
                    <statement>Example of an 'APE' style interface with hidden anchor 'zero' (which needs to be below 20%), looping of the samples, randomisation of marker labels, mandatory moving of every sample, and a forced scale usage of at least 25%-75%.</statement>
                </surveyentry>
            </survey>
            <survey location="after">
                <surveyentry type="question" id="genre-0" mandatory="true">
                    <statement>Please enter the genre.</statement>
                </surveyentry>
            </survey>
        </page>
        <page id='test-1' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='false' synchronous="true" label="letter">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface name="preference">
                <title>Example Test Question</title>
                <scales>
                    <scalelabel position="0">Min</scalelabel>
                    <scalelabel position="100">Max</scalelabel>
                    <scalelabel position="50">Middle</scalelabel>
                    <scalelabel position="20">20</scalelabel>
                </scales>
            </interface>
            <audioelement url="0.wav" gain="-6" id="track-5" type="anchor" marker="20" />
            <audioelement url="1.wav" gain="0.0" id="track-6" type="reference" marker="80" />
            <audioelement url="2.wav" gain="0.0" id="track-7" />
            <audioelement url="3.wav" gain="0.0" id="track-8" />
            <audioelement url="4.wav" gain="0.0" id="track-9" />
            <audioelement url="5.wav" gain="0.0" id="track-10" />
            <audioelement url="6.wav" gain="0.0" id="track-11" type="outside-reference" />
            <commentquestions>
                <commentquestion id='mixingExperience'>
                    <statement>What is your general experience with numbers?</statement>
                </commentquestion>
                <commentradio id="preference">
                    <statement>Please enter your overall preference</statement>
                    <option name="worst">Very Bad</option>
                    <option name="bad"></option>
                    <option name="OK">OK</option>
                    <option name="Good"></option>
                    <option name="Great">Great</option>
                </commentradio>
                <commentcheckbox id="character">
                    <statement>Please describe the overall character</statement>
                    <option name="funky">Funky</option>
                    <option name="mellow">Mellow</option>
                    <option name="laidback">Laid back</option>
                    <option name="heavy">Heavy</option>
                </commentcheckbox>
            </commentquestions>
            <survey location="before">
                <surveyentry type="statement" id="test-1-intro">
                    <statement>Example of an 'APE' style interface with hidden anchor 'zero' (which needs to be below 20%), looping of the samples, randomisation of marker labels, mandatory moving of every sample, and a forced scale usage of at least 25%-75%.</statement>
                </surveyentry>
            </survey>
            <survey location="after">
                <surveyentry type="question" id="genre-1" mandatory="true">
                    <statement>Please enter the genre.</statement>
                </surveyentry>
            </survey>
        </page>
    </waet>

=== BrechtDeMan/WebAudioEvaluationTool/example_eval/ABshort.xml
<?xml version="1.0" encoding="utf-8"?>
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
	<setup interface="AB" projectReturn="save.php" randomiseOrder='true' testPages="1" loudness="-23" sampleRate="44100">
		<metric>
			<metricenable>testTimer</metricenable>
			<metricenable>elementTimer</metricenable>
			<metricenable>elementInitialPosition</metricenable>
			<metricenable>elementTracker</metricenable>
			<metricenable>elementFlagListenedTo</metricenable>
			<metricenable>elementFlagMoved</metricenable>
			<metricenable>elementListenTracker</metricenable>
		</metric>
		<interface>
			<interfaceoption type="check" name="fragmentMoved"/>
			<interfaceoption type="check" name="scalerange" min="25" max="75"/>
            <interfaceoption type="check" name="fragmentPlayed" />
			<interfaceoption type="show" name='playhead'/>
			<interfaceoption type="show" name="page-count"/>
            <interfaceoption type="show" name='volume'/>
		</interface>
	</setup>
    <page id="test-0" hostURL="example_eval/" randomiseOrder="true" repeatCount="0" loop="false" showElementComments="true" loudness="-12">
        <commentboxprefix>Comment on fragment</commentboxprefix>
        <interface>
            <title>Which of these do you prefer</title>
        </interface>
        <audioelement url="3.wav" id="track-0"/>
        <audioelement url="5.wav" id="track-1"/>
    </page>
</waet>

=== BrechtDeMan/WebAudioEvaluationTool/html/tests/examples/timeline_example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
    <setup interface="timeline" projectReturn="save.php">
        <metric>
            <metricenable>testTimer</metricenable>
            <metricenable>elementTimer</metricenable>
            <metricenable>elementInitialPosition</metricenable>
            <metricenable>elementTracker</metricenable>
            <metricenable>elementFlagListenedTo</metricenable>
            <metricenable>elementFlagMoved</metricenable>
            <metricenable>elementListenTracker</metricenable>
        </metric>
        <interface>
            <interfaceoption type="check" name="fragmentPlayed" />
            <interfaceoption type="check" name="scalerange" min="25" max="75" />
            <interfaceoption type="show" name="volume" />
            <interfaceoption type="show" name='playhead' />
            <interfaceoption type="show" name="page-count" />
            <interfaceoption type="show" name="comments" />
        </interface>
    </setup>
    <page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
        <title>My Test</title>
        <interface>
            <scales>
                <scalelabel position="0">(1) Very Annoying</scalelabel>
                <scalelabel position="25">(2) Annoying</scalelabel>
                <scalelabel position="50">(3) Slightly Annoying</scalelabel>
                <scalelabel position="75">(4) Audible but not Annoying</scalelabel>
                <scalelabel position="100">(5) Inaudible</scalelabel>
            </scales>
        </interface>
        <audioelement url="0.wav" id="track-1" image="https://upload.wikimedia.org/wikipedia/commons/0/0a/Drumkit-icon.png" />
        <audioelement url="1.wav" id="track-2" image="https://upload.wikimedia.org/wikipedia/commons/0/0a/Drumkit-icon.png" />
        <commentquestions>
            <commentradio id="preference">
                <statement>Please enter your overall preference</statement>
                <option name="worst">Very Bad</option>
                <option name="bad"></option>
                <option name="OK">OK</option>
                <option name="Good"></option>
                <option name="Great">Great</option>
            </commentradio>
            <commentcheckbox id="character">
                <statement>Please describe the overall character</statement>
                <option name="funky">Funky</option>
                <option name="mellow">Mellow</option>
                <option name="laidback">Laid back</option>
                <option name="heavy">Heavy</option>
            </commentcheckbox>
        </commentquestions>
    </page>
    <page id='test-1' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
        <title>My Test</title>
        <interface>
            <scales>
                <scalelabel position="0">(1) Very Annoying</scalelabel>
                <scalelabel position="25">(2) Annoying</scalelabel>
                <scalelabel position="50">(3) Slightly Annoying</scalelabel>
                <scalelabel position="75">(4) Audible but not Annoying</scalelabel>
                <scalelabel position="100">(5) Inaudible</scalelabel>
            </scales>
        </interface>
        <audioelement url="0.wav" id="track-3" image="https://upload.wikimedia.org/wikipedia/commons/0/0a/Drumkit-icon.png" />
        <audioelement url="1.wav" id="track-4" image="https://upload.wikimedia.org/wikipedia/commons/0/0a/Drumkit-icon.png" />
        <commentquestions>
            <commentradio id="preference1">
                <statement>Please enter your overall preference</statement>
                <option name="worst">Very Bad</option>
                <option name="bad"></option>
                <option name="OK">OK</option>
                <option name="Good"></option>
                <option name="Great">Great</option>
            </commentradio>
            <commentcheckbox id="character1">
                <statement>Please describe the overall character</statement>
                <option name="funky">Funky</option>
                <option name="mellow">Mellow</option>
                <option name="laidback">Laid back</option>
                <option name="heavy">Heavy</option>
            </commentcheckbox>
        </commentquestions>
    </page>
</waet>

=== BrechtDeMan/WebAudioEvaluationTool/html/tests/templates/itur1116.xml
<?xml version="1.0" encoding="utf-8"?>
    <waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
        <setup interface="MUSHRA" projectReturn="save.php" randomiseOrder="true" loudness="-23">
            <exitText>Thank you for participating in this listening test. You may now exit the test environment</exitText>
            <metric>
                <metricenable>testTimer</metricenable>
                <metricenable>elementTimer</metricenable>
                <metricenable>elementInitialPosition</metricenable>
                <metricenable>elementTracker</metricenable>
                <metricenable>elementFlagListenedTo</metricenable>
                <metricenable>elementFlagMoved</metricenable>
                <metricenable>elementListenTracker</metricenable>
            </metric>
            <interface>
                <interfaceoption type="check" name="fragmentMoved" />
            </interface>
        </setup>
        <page id="training" randomiseOrder="true" repeatCount="0" loop="true" synchronous="true" position="0" label="capital">
            <interface>
                <title>Quality</title>
                <scales>
                    <scalelabel position="100">Imperceptible</scalelabel>
                    <scalelabel position="75">Perceptible but not annoying</scalelabel>
                    <scalelabel position="50">Slightly annoying</scalelabel>
                    <scalelabel position="25">Annoying</scalelabel>
                    <scalelabel position="0">Very annoying</scalelabel>
                </scales>
            </interface>
            <audioelement url="0.wav" id="training-A" type="reference" label="A" position="0" />
            <audioelement url="1.wav" id="training-1" />
            <audioelement url="0.wav" id="training-2" />
        </page>
        <page id="test-0" randomiseOrder="true" repeatCount="0" loop="true" synchronous="true" position="0" label="capital">
            <interface>
                <title>Quality</title>
                <scales>
                    <scalelabel position="100">Imperceptible</scalelabel>
                    <scalelabel position="75">Perceptible but not annoying</scalelabel>
                    <scalelabel position="50">Slightly annoying</scalelabel>
                    <scalelabel position="25">Annoying</scalelabel>
                    <scalelabel position="0">Very annoying</scalelabel>
                </scales>
            </interface>
            <audioelement url="0.wav" id="test-0-A" type="reference" label="A" position="0" />
            <audioelement url="1.wav" id="test-0-1" />
            <audioelement url="0.wav" id="test-0-2" />
        </page>
    </waet>
