=== BrechtDeMan/WebAudioEvaluationTool/test-schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- define simple elements-->
  <xs:element name="statement" type="xs:string"/>
  <xs:element name="metricenable" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  
  <!-- define simple attributes-->
  <xs:attribute name="id" type="xs:ID"/>
  <xs:attribute name="mandatory" type="xs:boolean"/>
  <xs:attribute name="name" type="xs:string"/>
  
  <!-- define complex elements-->
  <xs:element name="waet">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="setup" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="page" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="setup">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="survey" minOccurs="0" maxOccurs="2"/>
        <xs:element ref="metric" maxOccurs="1"/>
        <xs:element ref="interface" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="interface" type="xs:string" use="required"/>
      <xs:attribute name="projectReturn" type="xs:string" use="required"/>
      <xs:attribute name="randomiseOrder" type="xs:boolean" default="false"/>
      <xs:attribute name="testPages" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
      <xs:attribute name="sampleRate" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="page">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
        <xs:element name="commentboxprefix" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="interface" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="audioelement" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="commentquestion" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="survey" minOccurs="0" maxOccurs="2"/>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="hostURL" type="xs:anyURI" default=""/>
      <xs:attribute name="randomiseOrder" type="xs:boolean" default="false"/>
      <xs:attribute name="repeatCount" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="loop" type="xs:boolean" default="false"/>
      <xs:attribute name="showElementComments" type="xs:boolean" default="false"/>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="metric">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="metricenable" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="interface">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
        <xs:element name="interfaceoption" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="check"/>
                  <xs:enumeration value="show"/>
                  <xs:enumeration value="option"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute name="min" type="xs:decimal" use="optional"/>
            <xs:attribute name="max" type="xs:decimal" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="scales" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="scalelabel" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="position" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:nonNegativeInteger">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="100"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute ref="name" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="audioelement">
    <xs:complexType>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="url" type="xs:anyURI" use="required"/>
      <xs:attribute name="gain" type="xs:decimal" default="0"/>
      <xs:attribute name="type" default="normal">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="normal"/>
            <xs:enumeration value="anchor"/>
            <xs:enumeration value="reference"/>
            <xs:enumeration value="outside-reference"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="marker" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="commentquestion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="statement" minOccurs="0" maxOccurs="1"/>
        <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute ref="name"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="type" default="question">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="question"/>
            <xs:enumeration value="radio"/>
            <xs:enumeration value="checkbox"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="survey">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="surveyentry" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="statement" minOccurs="1" maxOccurs="1"/>
              <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="name"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute ref="id"/>
            <xs:attribute ref="mandatory"/>
            <xs:attribute name="min" type="xs:decimal"/>
            <xs:attribute name="max" type="xs:decimal"/>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="statement"/>
                  <xs:enumeration value="question"/>
                  <xs:enumeration value="number"/>
                  <xs:enumeration value="radio"/>
                  <xs:enumeration value="checkbox"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="boxsize" default="normal">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="normal"/>
                  <xs:enumeration value="large"/>
                  <xs:enumeration value="small"/>
                  <xs:enumeration value="huge"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="location">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="before"/>
            <xs:enumeration value="pre"/>
            <xs:enumeration value="after"/>
            <xs:enumeration value="post"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== BrechtDeMan/WebAudioEvaluationTool/example_eval/mushra_example.xml
<?xml version="1.0" encoding="utf-8"?>
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
	<setup interface="MUSHRA" projectReturn="save.php" randomiseOrder='true' testPages="2" loudness="-23" sampleRate="44100">
        <exitText>Thank you for looking at WAET. You can modify the successful completion text as well!</exitText>
		<survey location="before">
			<surveyentry type="question" id="sessionId" mandatory="true">
				<statement>Please enter your name.</statement>
			</surveyentry>
			<surveyentry type="checkbox" id="checkboxtest" mandatory="true">
				<statement>Please select with which activities you have any experience (example checkbox question)</statement>
				<option name="musician">Playing a musical instrument</option>
				<option name="soundengineer">Recording or mixing audio</option>
				<option name="developer">Developing audio software</option>
				<option name="hwdesigner">Designing or building audio hardware</option>
				<option name="researcher">Research in the field of audio</option>
			</surveyentry>
			<surveyentry type="statement" id="test-intro">
				<statement>This is an example of an 'APE'-style test, with two pages, using the test stimuli in 'example_eval/'.</statement>
			</surveyentry>
		</survey>
		<survey location="after">
			<surveyentry type="question" id="location" mandatory="true" boxsize="large">
				<statement>Please enter your location. (example mandatory text question)</statement>
			</surveyentry>
			<surveyentry type="number" id="age" min="0">
				<statement>Please enter your age (example non-mandatory number question)</statement>
			</surveyentry>
			<surveyentry type="radio" id="rating">
				<statement>Please rate this interface (example radio button question)</statement>
				<option name="bad">Bad</option>
				<option name="poor">Poor</option>
				<option name="good">Good</option>
				<option name="great">Great</option>
			</surveyentry>
			<surveyentry type="statement" id="thankyou">
				<statement>Thank you for taking this listening test. Please click 'submit' and your results will appear in the 'saves/' folder.</statement>
			</surveyentry>
		</survey>
		<metric>
			<metricenable>testTimer</metricenable>
			<metricenable>elementTimer</metricenable>
			<metricenable>elementInitialPosition</metricenable>
			<metricenable>elementTracker</metricenable>
			<metricenable>elementFlagListenedTo</metricenable>
			<metricenable>elementFlagMoved</metricenable>
			<metricenable>elementListenTracker</metricenable>
		</metric>
		<interface>
			<interfaceoption type="check" name="fragmentMoved"/>
			<interfaceoption type="check" name="scalerange" min="25" max="75"/>
			<interfaceoption type="show" name='playhead'/>
			<interfaceoption type="show" name="page-count"/>
            <interfaceoption type="show" name="volume"/>
		</interface>
	</setup>
	<page id='test-0' hostURL="example_eval/" randomiseOrder='true' repeatCount='0' loop='true' showElementComments='true' loudness="-12">
		<commentboxprefix>Comment on fragment</commentboxprefix>
		<interface>
			<scales>
				<scalelabel position="12">Much Worse</scalelabel>
				<scalelabel position="25">Worse</scalelabel>
				<scalelabel position="38">Slightly Worse</scalelabel>
				<scalelabel position="50">About the same</scalelabel>
				<scalelabel position="62">Slightly Better</scalelabel>
				<scalelabel position="75">Better</scalelabel>
				<scalelabel position="88">Much Better</scalelabel>
			</scales>
		</interface>
		<audioelement url="0.wav" id="track-0" type="anchor"/>
		<audioelement url="1.wav" id="track-1"/>
		<audioelement url="2.wav" id="track-2"/>
		<audioelement url="3.wav" id="track-3"/>
		<audioelement url="4.wav" id="track-4"/>
		<survey location="before">
			<surveyentry type="statement" id="test-0-intro">
				<statement>Example of a 'MUSHRA' style interface with hidden anchor 'zero' (which needs to be below 20%), looping of the samples, randomisation of marker labels, mandatory moving of every sample, and a forced scale usage of at least 25%-75% using a Comparison Category Rating Scale.</statement>
			</surveyentry>
		</survey>
		<survey location="after">
			<surveyentry type="question" id="genre-0" mandatory="true">
				<statement>Please enter the genre.</statement>
			</surveyentry>
		</survey>
	</page>
	<page id='test-1' hostURL="example_eval/" randomiseOrder='true' repeatCount='0' loop='false' showElementComments='true'>
		<commentboxprefix>Comment on fragment</commentboxprefix>
		<interface name="preference">
			<title>Example Test Question</title>
			<scales>
				<scalelabel position="0">Min</scalelabel>
				<scalelabel position="100">Max</scalelabel>
				<scalelabel position="50">Middle</scalelabel>
				<scalelabel position="20">20</scalelabel>
			</scales>
		</interface>
		<audioelement url="0.wav" gain="-6" id="track-5" type="anchor" marker="20"/>
		<audioelement url="1.wav" gain="0.0" id="track-6" type="reference" marker="80"/>
		<audioelement url="2.wav" gain="0.0" id="track-7"/>
		<audioelement url="3.wav" gain="0.0" id="track-8"/>
		<audioelement url="4.wav" gain="0.0" id="track-9"/>
		<audioelement url="5.wav" gain="0.0" id="track-10"/>
		<audioelement url="6.wav" gain="0.0" id="track-11" type="outside-reference"/>
		<commentquestion id='mixingExperience' type="question">
			<statement>What is your general experience with numbers?</statement>
		</commentquestion>
		<commentquestion id="preference" type="radio">
			<statement>Please enter your overall preference</statement>
			<option name="worst">Very Bad</option>
			<option name="bad"></option>
			<option name="OK">OK</option>
			<option name="Good"></option>
			<option name="Great">Great</option>
		</commentquestion>
		<commentquestion id="character" type="checkbox">
			<statement>Please describe the overall character</statement>
			<option name="funky">Funky</option>
			<option name="mellow">Mellow</option>
			<option name="laidback">Laid back</option>
			<option name="heavy">Heavy</option>
		</commentquestion>
		<survey location="before">
			<surveyentry type="statement" id="test-1-intro">
				<statement>Example of a 'MUSHRA' style interface with hidden anchor 'zero' (which needs to be below 20%), looping of the samples, randomisation of marker labels, mandatory moving of every sample, and a forced scale usage of at least 25%-75%.</statement>
			</surveyentry>
		</survey>
		<survey location="after">
			<surveyentry type="question" id="genre-1" mandatory="true">
				<statement>Please enter the genre.</statement>
			</surveyentry>
		</survey>
	</page>
</waet>

=== BrechtDeMan/WebAudioEvaluationTool/tests/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
	<setup interface="timeline" projectReturn="save.php" returnURL="http://localhost:8000/index.html?url=tests/test.xml">
		<metric>
			<metricenable>testTimer</metricenable>
			<metricenable>elementTimer</metricenable>
			<metricenable>elementInitialPosition</metricenable>
			<metricenable>elementTracker</metricenable>
			<metricenable>elementFlagListenedTo</metricenable>
			<metricenable>elementFlagMoved</metricenable>
			<metricenable>elementListenTracker</metricenable>
		</metric>
		<interface>
			<interfaceoption type="check" name="fragmentMoved"/>
			<interfaceoption type="check" name="scalerange" min="25" max="75"/>
            <interfaceoption type="show" name="volume"/>
			<interfaceoption type="show" name='playhead'/>
			<interfaceoption type="show" name="page-count"/>
            <interfaceoption type="show" name="comments"/>
		</interface>
	</setup>
	<page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
        <title>My Test</title>
		<interface>
			<scales>
				<scalelabel position="0">(1) Very Annoying</scalelabel>
				<scalelabel position="25">(2) Annoying</scalelabel>
				<scalelabel position="50">(3) Slightly Annoying</scalelabel>
				<scalelabel position="75">(4) Audible but not Annoying</scalelabel>
				<scalelabel position="100">(5) Inaudible</scalelabel>
			</scales>
		</interface>
		<audioelement url="0.wav" id="track-1"/>
		<audioelement url="1.wav" id="track-2"/>
        <commentquestion id="preference" type="radio">
			<statement>Please enter your overall preference</statement>
			<option name="worst">Very Bad</option>
			<option name="bad"></option>
			<option name="OK">OK</option>
			<option name="Good"></option>
			<option name="Great">Great</option>
		</commentquestion>
		<commentquestion id="character" type="checkbox">
			<statement>Please describe the overall character</statement>
			<option name="funky">Funky</option>
			<option name="mellow">Mellow</option>
			<option name="laidback">Laid back</option>
			<option name="heavy">Heavy</option>
		</commentquestion>
	</page>
    <page id='test-1' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
        <title>My Test</title>
		<interface>
			<scales>
				<scalelabel position="0">(1) Very Annoying</scalelabel>
				<scalelabel position="25">(2) Annoying</scalelabel>
				<scalelabel position="50">(3) Slightly Annoying</scalelabel>
				<scalelabel position="75">(4) Audible but not Annoying</scalelabel>
				<scalelabel position="100">(5) Inaudible</scalelabel>
			</scales>
		</interface>
		<audioelement url="0.wav" id="track-3"/>
		<audioelement url="1.wav" id="track-4"/>
        <commentquestion id="preference1" type="radio">
			<statement>Please enter your overall preference</statement>
			<option name="worst">Very Bad</option>
			<option name="bad"></option>
			<option name="OK">OK</option>
			<option name="Good"></option>
			<option name="Great">Great</option>
		</commentquestion>
		<commentquestion id="character1" type="checkbox">
			<statement>Please describe the overall character</statement>
			<option name="funky">Funky</option>
			<option name="mellow">Mellow</option>
			<option name="laidback">Laid back</option>
			<option name="heavy">Heavy</option>
		</commentquestion>
	</page>
</waet>

=== BrechtDeMan/WebAudioEvaluationTool/tests/examples/mushra_example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
    <setup interface="MUSHRA" projectReturn="save.php" randomiseOrder='true' poolSize="2" loudness="-23">
        <exitText>Thank you for looking at WAET. You can modify the successful completion text as well!</exitText>
        <survey location="before">
            <surveyquestion id="sessionId" mandatory="true">
                <statement>Please enter your name.</statement>
            </surveyquestion>
            <surveycheckbox id="checkboxtest" mandatory="true">
                <statement>Please select with which activities you have any experience (example checkbox question)</statement>
                <option name="musician">Playing a musical instrument</option>
                <option name="soundengineer">Recording or mixing audio</option>
                <option name="developer">Developing audio software</option>
                <option name="hwdesigner">Designing or building audio hardware</option>
                <option name="researcher">Research in the field of audio</option>
            </surveycheckbox>
            <surveystatement id="test-intro">
                <statement>This is an example of an 'MUSHRA'-style test, with two pages, using the test stimuli in 'example_eval/'.</statement>
            </surveystatement>
        </survey>
        <survey location="after">
            <surveyquestion id="location" mandatory="true" boxsize="large">
                <statement>Please enter your location. (example mandatory text question)</statement>
            </surveyquestion>
            <surveynumber id="age" min="0">
                <statement>Please enter your age (example non-mandatory number question)</statement>
            </surveynumber>
            <surveyradio id="rating">
                <statement>Please rate this interface (example radio button question)</statement>
                <option name="bad">Bad</option>
                <option name="poor">Poor</option>
                <option name="good">Good</option>
                <option name="great">Great</option>
            </surveyradio>
            <surveystatement id="thankyou">
                <statement>Thank you for taking this listening test. Please click 'Submit' and your results will appear in the 'saves/' folder.</statement>
            </surveystatement>
        </survey>
        <metric>
            <metricenable>testTimer</metricenable>
            <metricenable>elementTimer</metricenable>
            <metricenable>elementInitialPosition</metricenable>
            <metricenable>elementTracker</metricenable>
            <metricenable>elementFlagListenedTo</metricenable>
            <metricenable>elementFlagMoved</metricenable>
            <metricenable>elementListenTracker</metricenable>
        </metric>
        <interface>
            <interfaceoption type="check" name="fragmentMoved" />
            <interfaceoption type="check" name="scalerange" min="25" max="75" />
            <interfaceoption type="show" name="fragmentSort" />
            <interfaceoption type="show" name='playhead' />
            <interfaceoption type="show" name="page-count" />
            <interfaceoption type="show" name="volume" />
            <scales>
                <scalelabel position="12">Much Worse</scalelabel>
                <scalelabel position="25">Worse</scalelabel>
                <scalelabel position="38">Slightly Worse</scalelabel>
                <scalelabel position="50">About the same</scalelabel>
                <scalelabel position="62">Slightly Better</scalelabel>
                <scalelabel position="75">Better</scalelabel>
                <scalelabel position="88">Much Better</scalelabel>
            </scales>
        </interface>
    </setup>
    <page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='true' loudness="-12" restrictMovement="true">
        <commentboxprefix>Comment on fragment</commentboxprefix>
        <interface>
            <scales>
                <scalelabel position="12">Much Worse</scalelabel>
                <scalelabel position="25">Worse</scalelabel>
                <scalelabel position="38">Slightly Worse</scalelabel>
                <scalelabel position="50">About the same</scalelabel>
                <scalelabel position="62">Slightly Better</scalelabel>
                <scalelabel position="75">Better</scalelabel>
                <scalelabel position="88">Much Better</scalelabel>
            </scales>
        </interface>
        <audioelement url="0.wav" id="track-0" type="anchor" />
        <audioelement url="1.wav" id="track-1" />
        <audioelement url="2.wav" id="track-2" />
        <audioelement url="3.wav" id="track-3" />
        <audioelement url="4.wav" id="track-4" />
        <survey location="before">
            <surveyentry type="statement" id="test-0-intro">
                <statement>Example of a 'MUSHRA' style interface with hidden anchor 'zero' (which needs to be below 20%), looping of the samples, randomisation of marker labels, mandatory moving of every sample, and a forced scale usage of at least 25%-75% using a Comparison Category Rating Scale.</statement>
            </surveyentry>
        </survey>
        <survey location="after">
            <surveyentry type="question" id="genre-0" mandatory="true">
                <statement>Please enter the genre.</statement>
            </surveyentry>
        </survey>
    </page>
    <page id='test-1' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='false' restrictMovement="true">
        <commentboxprefix>Comment on fragment</commentboxprefix>
        <interface name="preference">
            <title>Example Test Question</title>
            <interfaceoption type="show" name="comments" />
            <scales>
                <scalelabel position="0">Min</scalelabel>
                <scalelabel position="100">Max</scalelabel>
                <scalelabel position="50">Middle</scalelabel>
                <scalelabel position="20">20</scalelabel>
            </scales>
        </interface>
        <audioelement url="0.wav" gain="-6.0" id="track-5" type="anchor" marker="20" />
        <audioelement url="1.wav" gain="0.0" id="track-6" type="reference" marker="80" />
        <audioelement url="2.wav" gain="0.0" id="track-7" />
        <audioelement url="3.wav" gain="0.0" id="track-8" />
        <audioelement url="4.wav" gain="0.0" id="track-9" />
        <audioelement url="5.wav" gain="0.0" id="track-10" />
        <audioelement url="1.wav" gain="0.0" id="track-11" type="outside-reference" />
        <commentquestions>
            <commentquestion id='mixingExperience'>
                <statement>What is your general experience with numbers?</statement>
            </commentquestion>
            <commentradio id="preference">
                <statement>Please enter your overall preference</statement>
                <option name="worst">Very Bad</option>
                <option name="bad"></option>
                <option name="OK">OK</option>
                <option name="Good"></option>
                <option name="Great">Great</option>
            </commentradio>
            <commentcheckbox id="character">
                <statement>Please describe the overall character</statement>
                <option name="funky">Funky</option>
                <option name="mellow">Mellow</option>
                <option name="laidback">Laid back</option>
                <option name="heavy">Heavy</option>
            </commentcheckbox>
        </commentquestions>
        <survey location="before">
            <surveyentry type="statement" id="test-1-intro">
                <statement>Example of a 'MUSHRA' style interface with hidden anchor 'zero' (which needs to be below 20%), looping of the samples, randomisation of marker labels, mandatory moving of every sample, and a forced scale usage of at least 25%-75%.</statement>
            </surveyentry>
        </survey>
        <survey location="after">
            <surveyentry type="question" id="genre-1" mandatory="true">
                <statement>Please enter the genre.</statement>
            </surveyentry>
        </survey>
    </page>
</waet>

=== BrechtDeMan/WebAudioEvaluationTool/html/tests/examples/ordinal_example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
    <setup interface="ordinal" projectReturn="save.php" randomiseOrder="true">
        <metric>
            <metricenable>testTimer</metricenable>
            <metricenable>elementTimer</metricenable>
            <metricenable>elementInitialPosition</metricenable>
            <metricenable>elementTracker</metricenable>
            <metricenable>elementFlagListenedTo</metricenable>
            <metricenable>elementFlagMoved</metricenable>
            <metricenable>elementListenTracker</metricenable>
        </metric>
        <interface>
            <interfaceoption type="check" name="fragmentComment" />
            <interfaceoption type="show" name='playhead' />
            <interfaceoption type="show" name="page-count" />
            <interfaceoption type="show" name="volume" />
            <interfaceoption type="show" name="comments" />
        </interface>
    </setup>
    <page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='true' loudness="-23">
        <title>Ordinal Evaluation</title>
        <interface></interface>
        <audioelement url="0.wav" id="track-1" />
        <audioelement url="1.wav" id="track-2" />
        <audioelement url="2.wav" id="track-3" />
        <audioelement url="3.wav" id="track-4" />
        <audioelement url="4.wav" id="track-5" />
        <audioelement url="5.wav" id="track-6" />
        <audioelement url="6.wav" id="track-7" />
        <audioelement url="7.wav" id="track-8" />
    </page>
</waet>
