=== BrechtDeMan/WebAudioEvaluationTool/test-schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- define simple elements-->
  <xs:element name="statement" type="xs:string"/>
  <xs:element name="metricenable" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  
  <!-- define simple attributes-->
  <xs:attribute name="id" type="xs:ID"/>
  <xs:attribute name="mandatory" type="xs:boolean"/>
  <xs:attribute name="name" type="xs:string"/>
  
  <!-- define complex elements-->
  <xs:element name="waet">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="setup" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="page" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="setup">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="survey" minOccurs="0" maxOccurs="2"/>
        <xs:element ref="metric" maxOccurs="1"/>
        <xs:element ref="interface" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="interface" type="xs:string" use="required"/>
      <xs:attribute name="projectReturn" type="xs:string" use="required"/>
      <xs:attribute name="randomiseOrder" type="xs:boolean" default="false"/>
      <xs:attribute name="testPages" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
      <xs:attribute name="sampleRate" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="page">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
        <xs:element name="commentboxprefix" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="interface" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="audioelement" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="commentquestion" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="survey" minOccurs="0" maxOccurs="2"/>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="hostURL" type="xs:anyURI" default=""/>
      <xs:attribute name="randomiseOrder" type="xs:boolean" default="false"/>
      <xs:attribute name="repeatCount" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="loop" type="xs:boolean" default="false"/>
      <xs:attribute name="showElementComments" type="xs:boolean" default="false"/>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="metric">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="metricenable" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="interface">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
        <xs:element name="interfaceoption" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="check"/>
                  <xs:enumeration value="show"/>
                  <xs:enumeration value="option"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute name="min" type="xs:decimal" use="optional"/>
            <xs:attribute name="max" type="xs:decimal" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="scales" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="scalelabel" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="position" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:nonNegativeInteger">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="100"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute ref="name" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="audioelement">
    <xs:complexType>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="url" type="xs:anyURI" use="required"/>
      <xs:attribute name="gain" type="xs:decimal" default="0"/>
      <xs:attribute name="type" default="normal">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="normal"/>
            <xs:enumeration value="anchor"/>
            <xs:enumeration value="reference"/>
            <xs:enumeration value="outside-reference"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="marker" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="loudness" type="xs:nonPositiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="commentquestion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="statement" minOccurs="0" maxOccurs="1"/>
        <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute ref="name"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute name="type" default="question">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="question"/>
            <xs:enumeration value="radio"/>
            <xs:enumeration value="checkbox"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="survey">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="surveyentry" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="statement" minOccurs="1" maxOccurs="1"/>
              <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="name"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute ref="id"/>
            <xs:attribute ref="mandatory"/>
            <xs:attribute name="min" type="xs:decimal"/>
            <xs:attribute name="max" type="xs:decimal"/>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="statement"/>
                  <xs:enumeration value="question"/>
                  <xs:enumeration value="number"/>
                  <xs:enumeration value="radio"/>
                  <xs:enumeration value="checkbox"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="boxsize" default="normal">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="normal"/>
                  <xs:enumeration value="large"/>
                  <xs:enumeration value="small"/>
                  <xs:enumeration value="huge"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="location">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="before"/>
            <xs:enumeration value="pre"/>
            <xs:enumeration value="after"/>
            <xs:enumeration value="post"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== BrechtDeMan/WebAudioEvaluationTool/html/tests/pool.xml
<?xml version="1.0" encoding="UTF-8" ?>
    <waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
        <setup interface="discrete" projectReturn="save.php" crossFade="0.1" poolSize="3">
            <metric>
                <metricenable>testTimer</metricenable>
                <metricenable>elementTimer</metricenable>
                <metricenable>elementInitialPosition</metricenable>
                <metricenable>elementTracker</metricenable>
                <metricenable>elementFlagListenedTo</metricenable>
                <metricenable>elementFlagMoved</metricenable>
                <metricenable>elementListenTracker</metricenable>
            </metric>
            <interface>
                <interfaceoption type="check" name="fragmentMoved" />
            </interface>
        </setup>
        <page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
            <interface>
                <scales>
                    <scalelabel position="0">(1) Very Annoying</scalelabel>
                    <scalelabel position="25">(2) Annoying</scalelabel>
                    <scalelabel position="50">(3) Slightly Annoying</scalelabel>
                    <scalelabel position="75">(4) Audible but not Annoying</scalelabel>
                    <scalelabel position="100">(5) Inaudible</scalelabel>
                </scales>
            </interface>
            <audioelement url="0.wav" id="track-1" name="track-0" type="outside-reference" />
            <audioelement url="1.wav" id="track-2" />
        </page>
        <page id='test-1' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
            <interface>
                <scales>
                    <scalelabel position="0">(1) Very Annoying</scalelabel>
                    <scalelabel position="25">(2) Annoying</scalelabel>
                    <scalelabel position="50">(3) Slightly Annoying</scalelabel>
                    <scalelabel position="75">(4) Audible but not Annoying</scalelabel>
                    <scalelabel position="100">(5) Inaudible</scalelabel>
                </scales>
            </interface>
            <audioelement url="0.wav" id="track-3" name="track-0" type="outside-reference" />
            <audioelement url="2.wav" id="track-4" />
        </page>
        <page id='test-2' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
            <interface>
                <scales>
                    <scalelabel position="0">(1) Very Annoying</scalelabel>
                    <scalelabel position="25">(2) Annoying</scalelabel>
                    <scalelabel position="50">(3) Slightly Annoying</scalelabel>
                    <scalelabel position="75">(4) Audible but not Annoying</scalelabel>
                    <scalelabel position="100">(5) Inaudible</scalelabel>
                </scales>
            </interface>
            <audioelement url="0.wav" id="track-5" name="track-0" type="outside-reference" />
            <audioelement url="3.wav" id="track-6" />
        </page>
        <page id='test-3' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
            <interface>
                <scales>
                    <scalelabel position="0">(1) Very Annoying</scalelabel>
                    <scalelabel position="25">(2) Annoying</scalelabel>
                    <scalelabel position="50">(3) Slightly Annoying</scalelabel>
                    <scalelabel position="75">(4) Audible but not Annoying</scalelabel>
                    <scalelabel position="100">(5) Inaudible</scalelabel>
                </scales>
            </interface>
            <audioelement url="0.wav" id="track-7" name="track-0" type="outside-reference" />
            <audioelement url="4.wav" id="track-8" />
        </page>
    </waet>

=== BrechtDeMan/WebAudioEvaluationTool/html/tests/examples/AB_example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
    <waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
        <setup interface="AB" projectReturn="save.php" returnURL="http://localhost:8000/test.html?url=tests/examples/AB_example.xml" randomiseOrder="false" poolSize="2" loudness="-23" playOne="true">
            <survey location="before">
                <surveyquestion id="sessionId" mandatory="true">
                    <statement>Please enter your name.</statement>
                </surveyquestion>
                <surveycheckbox id="checkboxtest" mandatory="true">
                    <statement>Please select with which activities you have any experience (example checkbox question)</statement>
                    <option name="musician">Playing a musical instrument</option>
                    <option name="soundengineer">Recording or mixing audio</option>
                    <option name="developer">Developing audio software</option>
                    <option name="hwdesigner">Designing or building audio hardware</option>
                    <option name="researcher">Research in the field of audio</option>
                </surveycheckbox>
                <surveystatement id="test-intro">
                    <statement>This is an example of an 'AB'-style test, with two pages, using the test stimuli in 'example_eval/'. The 'playOne' configuration option means a fragment has to be finished playing before another fragment can be auditioned. </statement>
                </surveystatement>
            </survey>
            <survey location="after">
                <surveyquestion id="location" mandatory="true" boxsize="large">
                    <statement>Please enter your location. (example mandatory text question)</statement>
                </surveyquestion>
                <surveynumber id="age" min="0">
                    <statement>Please enter your age (example non-mandatory number question)</statement>
                </surveynumber>
                <surveyradio id="rating">
                    <statement>Please rate this interface (example radio button question)</statement>
                    <option name="bad">Bad</option>
                    <option name="poor">Poor</option>
                    <option name="good">Good</option>
                    <option name="great">Great</option>
                </surveyradio>
                <surveystatement id="test-thank-you">
                    <statement>Thank you for taking this listening test. Please click 'Submit' and your results will appear in the 'saves/' folder.</statement>
                </surveystatement>
            </survey>
            <metric>
                <metricenable>testTimer</metricenable>
                <metricenable>elementTimer</metricenable>
                <metricenable>elementInitialPosition</metricenable>
                <metricenable>elementTracker</metricenable>
                <metricenable>elementFlagListenedTo</metricenable>
                <metricenable>elementFlagMoved</metricenable>
                <metricenable>elementListenTracker</metricenable>
            </metric>
            <interface>
                <interfaceoption type="show" name='playhead' />
                <interfaceoption type="show" name="page-count" />
                <interfaceoption type="show" name='volume' />
                <interfaceoption type="show" name='comments' />
            </interface>
        </setup>
        <page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='false' loudness="-12">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface>
                <title>Which sounds most like a drum?</title>
                <image src="https://upload.wikimedia.org/wikipedia/commons/0/0a/Drumkit-icon.png" />
            </interface>
            <audioelement url="0.wav" id="track-0" />
            <audioelement url="1.wav" id="track-1" />
            <survey location="before">
                <surveystatement id="test-0-intro">
                    <statement>A two way comparison using randomised element order, automatic loudness and synchronised looping. Also an embedded image</statement>
                </surveystatement>
            </survey>
            <survey location="after">
                <surveyquestion id="genre-0" mandatory="true">
                    <statement>Please enter the genre.</statement>
                </surveyquestion>
            </survey>
        </page>
        <page id='test-1' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='false' loudness="-12">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface>
                <title>Depth</title>
            </interface>
            <audioelement url="0.wav" id="track-2" />
            <audioelement url="1.wav" id="track-3" />
            <audioelement url="2.wav" id="track-4" />
            <audioelement url="3.wav" id="track-5" />
            <audioelement url="4.wav" id="track-6" />
            <audioelement url="5.wav" id="track-7" />
            <audioelement url="6.wav" id="track-8" />
            <survey location="before">
                <surveystatement id="test-1-intro">
                    <statement>A 7 way comparison using randomised element order and synchronised looping.</statement>
                </surveystatement>
            </survey>
            <survey location="after">
                <surveyquestion id="genre-1" mandatory="true">
                    <statement>Please enter the genre.</statement>
                </surveyquestion>
            </survey>
        </page>
    </waet>

=== BrechtDeMan/WebAudioEvaluationTool/tests/examples/ABX_example.xml
<?xml version="1.0" encoding="utf-8"?>
    <waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
        <setup interface="ABX" projectReturn="save.php" randomiseOrder='true' poolSize="2" loudness="-23">
            <survey location="before">
                <surveyentry type="question" id="sessionId" mandatory="true">
                    <statement>Please enter your name.</statement>
                </surveyentry>
                <surveyentry type="checkbox" id="checkboxtest" mandatory="true">
                    <statement>Please select with which activities you have any experience (example checkbox question)</statement>
                    <option name="musician">Playing a musical instrument</option>
                    <option name="soundengineer">Recording or mixing audio</option>
                    <option name="developer">Developing audio software</option>
                    <option name="hwdesigner">Designing or building audio hardware</option>
                    <option name="researcher">Research in the field of audio</option>
                </surveyentry>
                <surveyentry type="statement" id="test-intro">
                    <statement>This is an example of an 'ABX'-style test, with two pages, using the test stimuli in 'example_eval/'.</statement>
                </surveyentry>
            </survey>
            <survey location="after">
                <surveyentry type="question" id="location" mandatory="true" boxsize="large">
                    <statement>Please enter your location. (example mandatory text question)</statement>
                </surveyentry>
                <surveyentry type="number" id="age" min="0">
                    <statement>Please enter your age (example non-mandatory number question)</statement>
                </surveyentry>
                <surveyentry type="radio" id="rating">
                    <statement>Please rate this interface (example radio button question)</statement>
                    <option name="bad">Bad</option>
                    <option name="poor">Poor</option>
                    <option name="good">Good</option>
                    <option name="great">Great</option>
                </surveyentry>
                <surveyentry type="statement" id="test-thank-you">
                    <statement>Thank you for taking this listening test. Please click 'submit' and your results will appear in the 'saves/' folder.</statement>
                </surveyentry>
            </survey>
            <metric>
                <metricenable>testTimer</metricenable>
                <metricenable>elementTimer</metricenable>
                <metricenable>elementInitialPosition</metricenable>
                <metricenable>elementTracker</metricenable>
                <metricenable>elementFlagListenedTo</metricenable>
                <metricenable>elementFlagMoved</metricenable>
                <metricenable>elementListenTracker</metricenable>
            </metric>
            <interface>
                <interfaceoption type="check" name="fragmentMoved" />
                <interfaceoption type="check" name="scalerange" min="25" max="75" />
                <interfaceoption type="show" name='playhead' />
                <interfaceoption type="show" name="page-count" />
                <interfaceoption type="show" name='volume' />
                <interfaceoption type="show" name='comments' />
            </interface>
        </setup>
        <page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='true' loudness="-12">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface>
                <title>Depth</title>
            </interface>
            <audioelement url="0.wav" id="track-0" />
            <audioelement url="1.wav" id="track-1" />
            <survey location="before">
                <surveyentry type="statement" id="test-0-intro">
                    <statement>A two way comparison using randomised element order, automatic loudness and synchronised looping.</statement>
                </surveyentry>
            </survey>
            <survey location="after">
                <surveyentry type="question" id="genre-0" mandatory="true">
                    <statement>Please enter the genre.</statement>
                </surveyentry>
            </survey>
        </page>
        <page id='test-1' hostURL="media/example/" randomiseOrder='true' repeatCount='0' loop='false' loudness="-12">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface>
                <title>Depth</title>
            </interface>
            <audioelement url="0.wav" id="track-2" />
            <audioelement url="1.wav" id="track-3" />
            <survey location="before" />
            <survey location="after">
                <surveyentry type="question" id="genre-1" mandatory="true">
                    <statement>Please enter the genre.</statement>
                </surveyentry>
            </survey>
        </page>
    </waet>

=== BrechtDeMan/WebAudioEvaluationTool/html/tests/examples/radio_example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
    <setup interface="discrete" projectReturn="save.php" crossFade="3.0">
        <metric>
            <metricenable>testTimer</metricenable>
            <metricenable>elementTimer</metricenable>
            <metricenable>elementInitialPosition</metricenable>
            <metricenable>elementTracker</metricenable>
            <metricenable>elementFlagListenedTo</metricenable>
            <metricenable>elementFlagMoved</metricenable>
            <metricenable>elementListenTracker</metricenable>
        </metric>
        <interface>
            <interfaceoption type="check" name="fragmentMoved" />
            <interfaceoption type="check" name="scalerange" min="25" max="75" />
            <interfaceoption type="show" name="volume" />
            <interfaceoption type="show" name='playhead' />
            <interfaceoption type="show" name="page-count" />
            <interfaceoption type="show" name="comments" />
        </interface>
    </setup>
    <page id='test-0' hostURL="media/example/" randomiseOrder='true' repeatCount='4' loop='true' loudness="-23">
        <interface>
            <scales>
                <scalelabel position="0">(1) Very Annoying</scalelabel>
                <scalelabel position="25">(2) Annoying</scalelabel>
                <scalelabel position="50">(3) Slightly Annoying</scalelabel>
                <scalelabel position="75">(4) Audible but not Annoying</scalelabel>
                <scalelabel position="100">(5) Inaudible</scalelabel>
            </scales>
        </interface>
        <audioelement url="0.wav" id="track-0" alwaysInclude="true" />
        <audioelement url="1.wav" id="track-1" />
        <audioelement url="2.wav" id="track-2" />
        <audioelement url="3.wav" id="track-3" />
    </page>
</waet>

=== BrechtDeMan/WebAudioEvaluationTool/example_eval/pre_survey.xml
<?xml version="1.0" encoding="utf-8"?>
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
	<setup interface="AB" projectReturn="save.php" randomiseOrder='true' testPages="1" loudness="-23" sampleRate="44100">
		<survey location="before">
			<surveyentry type="question" id="sessionId" mandatory="true">
				<statement>Please enter your name.</statement>
			</surveyentry>
			<surveyentry type="checkbox" id="checkboxtest" mandatory="true">
				<statement>Please select with which activities you have any experience (example checkbox question)</statement>
				<option name="musician">Playing a musical instrument</option>
				<option name="soundengineer">Recording or mixing audio</option>
				<option name="developer">Developing audio software</option>
				<option name="hwdesigner">Designing or building audio hardware</option>
				<option name="researcher">Research in the field of audio</option>
			</surveyentry>
            <surveyentry type="statement" id="pre-survey">
				<statement>This is a preliminary test for a study on the Hammond organ. You will be presented with pairs of stimuli. For each pair you will be asked to single out the one note that was produced by a heavier touch.
                    
                    Feel free to add any comments on the stimuli in the boxes at the bottom of each page of the test.	</statement>
			</surveyentry>
		</survey>
		<metric>
			<metricenable>testTimer</metricenable>
			<metricenable>elementTimer</metricenable>
			<metricenable>elementInitialPosition</metricenable>
			<metricenable>elementTracker</metricenable>
			<metricenable>elementFlagListenedTo</metricenable>
			<metricenable>elementFlagMoved</metricenable>
			<metricenable>elementListenTracker</metricenable>
		</metric>
		<interface>
			<interfaceoption type="check" name="fragmentMoved"/>
			<interfaceoption type="check" name="scalerange" min="25" max="75"/>
            <interfaceoption type="check" name="fragmentPlayed" />
			<interfaceoption type="show" name='playhead'/>
			<interfaceoption type="show" name="page-count"/>
            <interfaceoption type="show" name='volume'/>
            <!--interfaceoption type="submit" name="post-submit-dialog">
                <a href="javascript:document.referrer">Click here to continue with the next test</a>
            </interfaceoption-->
		</interface>
	</setup>
    <page id="test-0" hostURL="example_eval/" hidden="true">
        <interface>
            <title>Pre-test survey</title>
        </interface>
        <audioelement url="1.wav" id="track-1"/>
    </page>
</waet>
